### ISSUE TITLE
ArgumentError when RubyProf::CallTreePrinter is used

### ISSUE THREAD

**Issue by alagos** [sinisterchipmunk/rspec-prof#23]
I've followed the guide in https://github.com/sinisterchipmunk/rspec-prof#configuration to configure another printer, but it throws the following:
```
     ArgumentError:
       wrong number of arguments (2 for 0..1)
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46:in `print'
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:48:in `block in save_to'
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:46:in `open'
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:46:in `save_to'
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:18:in `profile'
     # /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:74:in `block (2 levels) in <top (required)>'
```

**Comment by lporras** [comment]
@alagos this happens because the method print for RubyProf::CallTreePrinter, do no accept a file as argument anymore

See:
https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/printers/call_tree_printer.rb#L54

and in this line:

https://github.com/sinisterchipmunk/rspec-prof/blob/master/lib/rspec-prof.rb#L48

the library is trying to generate the report using a generated file.
